Методичка 2.1

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

A)A  — матрица 4×2, B — матрица 4×2;  AB нельзя, BA нельзя

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;  AB можно - матрица 2х3 , BA нельзя 

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ; Можно и то и то, AB - 8x8 BA-3x3

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 . ; Можно и то и то, итоговые 4х4

2. Найти сумму и произведение матриц  A  и  B

In [3]:
import numpy as np
A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])
A+B, A@B


(array([[ 5, -3],
        [ 3,  5]]),
 array([[  4, -11],
        [ 12,  -3]]))

3. Вычислить линейную комбинацию  3A−2B+4C

In [6]:
A=np.array([[1,7],[3,-6]])
B=np.array([[0,5],[2,-1]])
C=np.array([[2,-4],[1,1]])
D=3*A-2*B+4*C
D

array([[ 11,  -5],
       [  9, -12]])

4.Вычислить  AAT  и  ATA .

In [10]:
A=np.array([[4,1],[5,-2],[2,3]])
AT=A.T
AAT=A@AT
ATA=AT@A
AAT,ATA

(array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]),
 array([[45,  0],
        [ 0, 14]]))

Методичка 2.2

1. Вычислить определитель:

a)  DET(A) = Sin^2x+Cos^2x = 1
   

b)

In [13]:
A=np.array([[4,2,3],[0,5,1],[0,0,9]])
DETA=np.linalg.det(A)
DETA

180.0

в)

In [14]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
DETA=np.linalg.det(A)
DETA

-9.51619735392994e-16

2.Определитель матрицы  A  равен  4 . Найти:

a) det(A2) ; detA=det(A^2)

b) det(AT); det(A)=det(AT)

в)det(2A) ; det A=4  det 2A=16

3.Доказать, что матрица вырожденная.

In [17]:
A=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
DETA=np.linalg.det(A)
DETA!=0

False

Матрица не вырожденная, опеределитель не равен нулю

4.Найти ранг матрицы:

In [21]:
A=np.array([[1,2,3],[1,1,1],[2,3,4]])
B=np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
ranka=np.linalg.matrix_rank(A)
rankb=np.linalg.matrix_rank(B)
ranka,rankb

(2, 3)